# Site settings
title: I Saw An Eric
author: Eric An
author_link: http://eric-an.github.io/
author_description: There's no better practice than repetition.
description: A blog by an aspiring web developer.
baseurl: /blog # the subpath of your site, e.g. /blog
url: http://eric-an.github.io/ # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id:

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty

# Pagination
paginate: 15

# Sass
sass:
    style: :compressed
